# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
       containerRegistry: 'hub connection'
       repository: 'abhi2322/projectt'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'

- stage: Setup
  jobs:
    - job: Setup
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'Latest'

      
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'abhishek-hub'
          backendAzureRmResourceGroupName: 'NetworkWatcherRG'
          backendAzureRmStorageAccountName: 'abhishekstorageacc'
          backendAzureRmContainerName: 'terraform-container'
          backendAzureRmKey: 'tf/terraform.tfstate'
      
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'abhishek-hub'
      
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'abhishek-hub'


